name: UUIDChecker
version: '${project.version}'
main: me.hephaestus.uuidchecker.UUIDChecker
api-version: 1.18
commands:
  UUID:
    description: gets the uuid of a player
    usage: /<command>
    permission: UUIDChecker.uuid